param([string]$Repository = (Get-Location).Path)

Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'
. (Join-Path $PSScriptRoot 'common.ps1')

function Save-BugLedger { param($Ledger,$Paths) $Ledger.revision=[int]$Ledger.revision+1; Write-RalphJsonAtomic $Paths.Bugs $Ledger (Join-Path $Paths.Schemas 'bugs.schema.json') }
function Get-KnownMergeShas { param($Tasks,$Bugs) @(@($Tasks.tasks)+@($Bugs.bugs)|Where-Object{$null-ne$_.pullRequest-and$_.pullRequest.mergeSha}|ForEach-Object{[string]$_.pullRequest.mergeSha}) }
function Remove-CompletedAssignmentArtifacts {
    param($Root,$Configuration,$Tasks,$Bugs)
    foreach($item in @($Tasks.tasks)+@($Bugs.bugs)) {
        $id=if($item.PSObject.Properties['taskId']){[string]$item.taskId}else{[string]$item.bugId}
        if($item.branch){$base=Get-RalphWorktreeBase $Root $Configuration;$path=Join-Path $base $id;if([IO.Directory]::Exists($path)-or(Invoke-RalphNative git @('-C',$Root,'show-ref','--verify','--quiet',"refs/heads/$($item.branch)")-AllowedExitCodes @(0,1)).ExitCode-eq0){Remove-RalphWorktree $Root $Configuration $id ([string]$item.branch)}}
        if($item.branch-and[bool]$Configuration.deleteMergedBranches){[void](Invoke-RalphNative git @('-C',$Root,'fetch',[string]$Configuration.remote,'--prune'));$remoteRef="refs/remotes/$($Configuration.remote)/$($item.branch)";if((Invoke-RalphNative git @('-C',$Root,'show-ref','--verify','--quiet',$remoteRef)-AllowedExitCodes @(0,1)).ExitCode-eq0){[void](Invoke-RalphNative git @('-C',$Root,'push',[string]$Configuration.remote,'--delete',[string]$item.branch));[void](Invoke-RalphNative git @('-C',$Root,'fetch',[string]$Configuration.remote,'--prune'));if((Invoke-RalphNative git @('-C',$Root,'show-ref','--verify','--quiet',$remoteRef)-AllowedExitCodes @(0,1)).ExitCode-eq0){throw "Remote assignment branch survived final cleanup: $($item.branch)"}}}
    }
}
function Complete-ProjectCleanup {
    param($Root,$Configuration,$Tasks,$Bugs,$FinalSha)
    Remove-CompletedAssignmentArtifacts $Root $Configuration $Tasks $Bugs
    [void](Invoke-RalphNative git @('-C',$Root,'fetch',[string]$Configuration.remote,'--prune'))
    $current=(Invoke-RalphNative git @('-C',$Root,'branch','--show-current')).Output.Trim()
    if($current-ceq[string]$Configuration.targetBranch){[void](Invoke-RalphNative git @('-C',$Root,'merge','--ff-only',"$($Configuration.remote)/$($Configuration.targetBranch)"))}else{[void](Invoke-RalphNative git @('-C',$Root,'branch','-f',[string]$Configuration.targetBranch,$FinalSha))}
    if((Invoke-RalphNative git @('-C',$Root,'show-ref','--verify','--quiet',"refs/heads/$($Configuration.integrationBranch)")-AllowedExitCodes @(0,1)).ExitCode-eq0){[void](Invoke-RalphNative git @('-C',$Root,'branch','-D','--',[string]$Configuration.integrationBranch))}
    if((Invoke-RalphNative git @('-C',$Root,'show-ref','--verify','--quiet',"refs/remotes/$($Configuration.remote)/$($Configuration.integrationBranch)")-AllowedExitCodes @(0,1)).ExitCode-eq0-and[bool]$Configuration.deleteMergedBranches){[void](Invoke-RalphNative git @('-C',$Root,'push',[string]$Configuration.remote,'--delete',[string]$Configuration.integrationBranch))}
    Remove-RalphEmptyWorktreeContainers $Root $Configuration
    $base=Get-RalphWorktreeBase $Root $Configuration;if([IO.Directory]::Exists($base)-and@(Get-ChildItem $base -Force).Count){throw 'Owned worktree cleanup left orphaned directories.'}
}

$root=Get-RalphRepositoryRoot $Repository;$configuration=Get-RalphConfiguration $root;Assert-RalphPrerequisites $configuration -RequireCodex
if(-not(Get-Command Start-ThreadJob -ErrorAction SilentlyContinue)){throw 'PowerShell ThreadJob support is required for concurrent bug fixers.'}
$paths=Initialize-RalphStateFiles $root $configuration;$lock=Enter-RalphWorkflowLock $paths.Lock;$state=$null;$bugs=$null;$auditWorktree=$null

try {
    $state=Read-RalphJson $paths.State (Join-Path $paths.Schemas 'state.schema.json');$tasks=Read-RalphJson $paths.Tasks (Join-Path $paths.Schemas 'tasks.schema.json');$bugs=Read-RalphJson $paths.Bugs (Join-Path $paths.Schemas 'bugs.schema.json')
    Assert-RalphStateIdentity $state $root $configuration;Assert-RalphPlanDrift $state $root -RequirePlan;Assert-RalphLedgerIdentity $state $tasks task
    if([string]$tasks.status-cne'complete'-or@($tasks.tasks|Where-Object { $_.status -ne 'integrated' }).Count){throw 'Every implementation task must be integrated before audit begins.'}
    if([string]$state.stage-ceq'complete'){Show-RalphStatus $state $tasks $bugs;Write-Host 'PROJECT COMPLETE: audit, bug fixes, validation, and final merge are finished.';return}
    if([string]$state.stage-notin@('audit','blocked')){throw "The workflow is at stage $($state.stage), not audit."}

    # If the final PR merged immediately before a crash, verify it instead of reporting target drift.
    [void](Invoke-RalphNative git @('-C',$root,'fetch',[string]$configuration.remote,'--prune'));$currentTarget=(Invoke-RalphNative git @('-C',$root,'rev-parse',"$($configuration.remote)/$($configuration.targetBranch)")).Output.Trim()
    if($state.targetBaseSha-and$currentTarget-cne[string]$state.targetBaseSha-and$state.integrationSha){
        $finalPr=Get-RalphPullRequest $root $configuration ([string]$configuration.integrationBranch) ([string]$configuration.targetBranch) ([string]$state.integrationSha)
        if($null-eq$finalPr-or[string]$finalPr.state-notin@('merged','completed')){throw 'Target branch advanced without the exact workflow project pull request.'}
        $finalPr=Complete-RalphPullRequest $root $configuration $finalPr;Complete-ProjectCleanup $root $configuration $tasks $bugs ([string]$finalPr.mergeSha)
        $state.stage='complete';$state.stageStatus='complete';$state.finalMergeSha=[string]$finalPr.mergeSha;$state.blocker=$null;Save-RalphState $state $paths
        Write-RalphSummary $paths.AuditSummary ([ordered]@{completedAt=[DateTimeOffset]::UtcNow.ToString('O');recoveredAfterFinalMerge=$true;totalBugs=@($bugs.bugs).Count;verifiedBugs=@($bugs.bugs|Where-Object { $_.status -eq 'verified' }).Count;projectPullRequest=$finalPr;finalMergeSha=$state.finalMergeSha})
        Show-RalphStatus $state $tasks $bugs;Write-Host 'PROJECT COMPLETE: recovered and verified the final project merge.';return
    }
    [void](Assert-RalphTargetDrift $root $configuration $state)
    $state.stage='audit';$state.stageStatus='running';$state.blocker=$null;$state.integrationSha=Ensure-RalphIntegrationBranch $root $configuration $state (Get-KnownMergeShas $tasks $bugs);Save-RalphState $state $paths

    if([string]$bugs.status-ceq'not_audited'){
        $auditWorktree=New-RalphAuditWorktree $root $configuration "$($configuration.remote)/$($configuration.integrationBranch)";$context="Audit the complete implementation at exact integration commit $($state.integrationSha). Return the complete bounded finding set in one response. Do not edit the worktree.";$auditResult=Invoke-RalphRole $root $auditWorktree 'auditor' $context 'audit-result.schema.json' 'read-only'
        Assert-RalphPlanDrift $state $root -RequirePlan;Assert-RalphLedgerIdentity $state $tasks task;[void](Assert-RalphTargetDrift $root $configuration $state);$unchanged=Ensure-RalphIntegrationBranch $root $configuration $state (Get-KnownMergeShas $tasks $bugs);if($unchanged-cne[string]$state.integrationSha){throw 'Integration changed while the deep audit was running.'}
        if(@($auditResult.bugs).Count){Assert-RalphGraph @($auditResult.bugs) bug}
        $persisted=foreach($bug in @($auditResult.bugs)){[ordered]@{bugId=[string]$bug.bugId;title=[string]$bug.title;severity=[string]$bug.severity;category=[string]$bug.category;status='open';disposition=$null;requirementIds=@($bug.requirementIds);description=[string]$bug.description;evidence=[string]$bug.evidence;actualBehavior=[string]$bug.actualBehavior;requiredBehavior=[string]$bug.requiredBehavior;impact=[string]$bug.impact;requiredCorrection=[string]$bug.requiredCorrection;acceptanceTest=[string]$bug.acceptanceTest;dependencies=@($bug.dependencies);allowedPaths=@($bug.allowedPaths);exclusiveResources=@($bug.exclusiveResources);attemptCount=0;branch=$null;worktree=$null;baseSha=$null;resultSha=$null;pullRequest=$null;lastError=$null}}
        $definitionHash=Get-RalphDefinitionHash @($persisted) bug;$bugs=[ordered]@{schemaVersion='1.0';revision=[int]$bugs.revision+1;auditSha=[string]$state.integrationSha;definitionHash=$definitionHash;status='ready';bugs=@($persisted)};$state.bugDefinitionHash=$definitionHash
        Write-RalphJsonAtomic $paths.Bugs $bugs (Join-Path $paths.Schemas 'bugs.schema.json');Save-RalphState $state $paths;Remove-RalphAuditWorktree $root $configuration;$auditWorktree=$null
    } else {if(-not$bugs.auditSha){throw 'Existing bug ledger has no audit SHA.'};Assert-RalphLedgerIdentity $state $bugs bug;if(@($bugs.bugs).Count){Assert-RalphGraph @($bugs.bugs) bug}}

    foreach($bug in @($bugs.bugs|Where-Object { $_.status -eq 'active' })){$record=Read-RalphAttemptResult $paths ([string]$bug.bugId) ([int]$bug.attemptCount);if($null-ne$record-and[bool]$record.succeeded){$bug.status='result_ready'}else{$bug.status='open';$bug.lastError=if($null-eq$record){'Interrupted before a durable result was produced.'}else{[string]$record.error}}}
    foreach($bug in @($bugs.bugs|Where-Object { $_.status -in @('ready_to_publish','result_ready') })){
        if($bug.resultSha){$existing=Get-RalphPullRequest $root $configuration ([string]$bug.branch) ([string]$configuration.integrationBranch) ([string]$bug.resultSha);if($existing){$merged=Complete-RalphPullRequest $root $configuration $existing;$bug.pullRequest=$merged;$bug.status='verified';$bug.lastError=$null;$state.integrationSha=[string]$merged.mergeSha;Save-BugLedger $bugs $paths;Save-RalphState $state $paths;try{Remove-RalphMergedAssignment $root $configuration ([string]$bug.bugId) ([string]$bug.branch) $merged}catch{Write-Warning $_.Exception.Message}}}
    }
    foreach($bug in @($bugs.bugs|Where-Object { $_.status -eq 'ready_to_publish' })){
        Assert-RalphPlanDrift $state $root -RequirePlan;Assert-RalphLedgerIdentity $state $bugs bug;[void](Assert-RalphTargetDrift $root $configuration $state)
        $merged=Publish-RalphAssignment $root ([string]$bug.worktree) $configuration $bug bug;$bug.pullRequest=$merged;$bug.status='verified';$bug.lastError=$null;$state.integrationSha=[string]$merged.mergeSha
        Save-BugLedger $bugs $paths;Save-RalphState $state $paths;try{Remove-RalphMergedAssignment $root $configuration ([string]$bug.bugId) ([string]$bug.branch) $merged}catch{Write-Warning $_.Exception.Message}
    }
    Save-BugLedger $bugs $paths;$state.integrationSha=Ensure-RalphIntegrationBranch $root $configuration $state (Get-KnownMergeShas $tasks $bugs);Save-RalphState $state $paths

    while(@($bugs.bugs|Where-Object { $_.status -ne 'verified' }).Count){
        Assert-RalphPlanDrift $state $root -RequirePlan;Assert-RalphLedgerIdentity $state $tasks task;Assert-RalphLedgerIdentity $state $bugs bug;[void](Assert-RalphTargetDrift $root $configuration $state);$state.integrationSha=Ensure-RalphIntegrationBranch $root $configuration $state (Get-KnownMergeShas $tasks $bugs)
        foreach($bug in @($bugs.bugs|Where-Object { $_.status -eq 'result_ready' })){
            $record=Read-RalphAttemptResult $paths ([string]$bug.bugId) ([int]$bug.attemptCount);if($null-eq$record-or-not[bool]$record.succeeded){$bug.status='open';continue};$result=$record.result
            try{
                if([string]$result.status-ceq'blocked'){throw [string]$result.blocker}
                if([string]$result.status-ceq'not_reproducible'){$context='Verify only this not-reproducible disposition:'+[Environment]::NewLine+($bug|ConvertTo-Json -Depth 50)+[Environment]::NewLine+($result|ConvertTo-Json -Depth 50);$verification=Invoke-RalphRole $root ([string]$bug.worktree) 'verifier' $context 'verifier-result.schema.json' 'read-only';if(-not[bool]$verification.approved){throw "Not-reproducible disposition was rejected: $(@($verification.findings)-join'; ')"};Assert-RalphPlanDrift $state $root -RequirePlan;Assert-RalphLedgerIdentity $state $bugs bug;[void](Assert-RalphTargetDrift $root $configuration $state);$bug.disposition='not_reproducible';$bug.status='verified';$bug.lastError=$null;Remove-RalphWorktree $root $configuration ([string]$bug.bugId) ([string]$bug.branch);continue}
                $commit=Assert-RalphAssignmentCommit ([string]$bug.worktree) ([string]$bug.baseSha) $bug;if([string]$result.commitSha-cne[string]$commit.Head){throw 'Fixer result commit SHA does not match worktree HEAD.'};$bug.resultSha=[string]$commit.Head
                $context='Verify only this bug correction:'+[Environment]::NewLine+($bug|ConvertTo-Json -Depth 50)+[Environment]::NewLine+($result|ConvertTo-Json -Depth 50);$verification=Invoke-RalphRole $root ([string]$bug.worktree) 'verifier' $context 'verifier-result.schema.json' 'read-only';if(-not[bool]$verification.approved){throw "Bug verification failed: $(@($verification.findings)-join'; ')"}
                Assert-RalphPlanDrift $state $root -RequirePlan;Assert-RalphLedgerIdentity $state $bugs bug;[void](Assert-RalphTargetDrift $root $configuration $state);$bug.disposition='fixed';$bug.status='ready_to_publish';Save-BugLedger $bugs $paths
                $state.integrationSha=Ensure-RalphIntegrationBranch $root $configuration $state (Get-KnownMergeShas $tasks $bugs);$merged=Publish-RalphAssignment $root ([string]$bug.worktree) $configuration $bug bug;$bug.pullRequest=$merged;$bug.status='verified';$bug.lastError=$null;$state.integrationSha=[string]$merged.mergeSha;Save-BugLedger $bugs $paths;Save-RalphState $state $paths;try{Remove-RalphMergedAssignment $root $configuration ([string]$bug.bugId) ([string]$bug.branch) $merged}catch{Write-Warning $_.Exception.Message}
            }catch{$bug.status=if($bug.disposition-eq'fixed'-and$bug.resultSha){'ready_to_publish'}else{'open'};$bug.lastError=$_.Exception.Message}
        }
        Save-BugLedger $bugs $paths;if(@($bugs.bugs|Where-Object { $_.status -ne 'verified' }).Count-eq0){break}
        $exhausted=@($bugs.bugs|Where-Object{$_.status-ne'verified'-and[int]$_.attemptCount-ge[int]$configuration.maximumBugAttempts});if($exhausted){foreach($bug in $exhausted){$bug.status='blocked'};$bugs.status='blocked';Save-BugLedger $bugs $paths;throw "Bug attempts exhausted: $(@($exhausted.bugId)-join', ')"}
        $wave=@(Select-RalphReadyItems @($bugs.bugs) bug ([int]$configuration.maximumConcurrentFixers));if(-not$wave){throw 'No dependency-ready, non-conflicting bugs remain.'};$baseSha=[string]$state.integrationSha
        foreach($bug in $wave){if(-not$bug.branch){$bug.branch="worktree/$($bug.bugId)"};if(-not$bug.baseSha){$bug.baseSha=$baseSha};$bug.worktree=New-RalphWorktree $root $configuration ([string]$bug.bugId) ([string]$bug.branch) ([string]$bug.baseSha) ([string]$bug.resultSha);$bug.attemptCount=[int]$bug.attemptCount+1;$bug.status='active';$bug.lastError=$null;$assignment=[ordered]@{schemaVersion='1.0';identity=[string]$bug.bugId;attempt=[int]$bug.attemptCount;baseSha=[string]$bug.baseSha;startingHead=(Invoke-RalphNative git @('-C',[string]$bug.worktree,'rev-parse','HEAD')).Output.Trim();createdAt=[DateTimeOffset]::UtcNow.ToString('O');item=$bug};Write-RalphImmutableJson (Get-RalphAttemptPath $paths assignment ([string]$bug.bugId) ([int]$bug.attemptCount)) $assignment};$bugs.status='active';Save-BugLedger $bugs $paths
        $jobs=foreach($bug in $wave){$json=$bug|ConvertTo-Json -Depth 50 -Compress;$resultPath=Get-RalphAttemptPath $paths result ([string]$bug.bugId) ([int]$bug.attemptCount);Start-ThreadJob -Name ([string]$bug.bugId) -ArgumentList @($PSScriptRoot,$root,[string]$bug.worktree,$json,$resultPath) -ScriptBlock{param($ScriptsPath,$RepositoryRoot,$Worktree,$BugJson,$ResultPath);.(Join-Path $ScriptsPath 'common.ps1');$bug=$BugJson|ConvertFrom-Json -Depth 50;$context='Bug assignment:'+[Environment]::NewLine+($bug|ConvertTo-Json -Depth 50);try{$result=Invoke-RalphRole $RepositoryRoot $Worktree 'bug-fixer' $context 'fixer-result.schema.json' 'workspace-write';$record=[ordered]@{schemaVersion='1.0';identity=[string]$bug.bugId;attempt=[int]$bug.attemptCount;succeeded=$true;result=$result;error=$null;completedAt=[DateTimeOffset]::UtcNow.ToString('O')}}catch{$record=[ordered]@{schemaVersion='1.0';identity=[string]$bug.bugId;attempt=[int]$bug.attemptCount;succeeded=$false;result=$null;error=$_.Exception.Message;completedAt=[DateTimeOffset]::UtcNow.ToString('O')}};Write-RalphImmutableJson $ResultPath $record;$record}}
        $outer=([int]$configuration.agentTimeoutMinutes*60)+[int]$configuration.agentCleanupGraceSeconds+30;try{[void](Wait-Job $jobs -Timeout $outer);foreach($job in $jobs){$bug=@($wave|Where-Object { $_.bugId -eq $job.Name })[0];if($job.State-ne'Completed'){Stop-Job $job -ErrorAction SilentlyContinue;$bug.status='open';$bug.lastError='Bug fixer did not stop after the bounded deadline.';continue};$record=Receive-Job $job;if($null-eq$record-or-not[bool]$record.succeeded){$bug.status='open';$bug.lastError=if($null-eq$record){'Bug fixer returned no durable result.'}else{[string]$record.error}}else{$bug.status='result_ready'}}}finally{$jobs|ForEach-Object{if($_.State-ne'Completed'){Stop-Job $_ -ErrorAction SilentlyContinue};Remove-Job $_ -Force -ErrorAction SilentlyContinue}};Save-BugLedger $bugs $paths;Show-RalphStatus $state $tasks $bugs
    }

    Assert-RalphPlanDrift $state $root -RequirePlan;Assert-RalphLedgerIdentity $state $bugs bug;[void](Assert-RalphTargetDrift $root $configuration $state);$state.integrationSha=Ensure-RalphIntegrationBranch $root $configuration $state (Get-KnownMergeShas $tasks $bugs);$bugs.status='complete';Save-BugLedger $bugs $paths
    $auditWorktree=New-RalphAuditWorktree $root $configuration "$($configuration.remote)/$($configuration.integrationBranch)";$context="Run final project validation at exact integration SHA $($state.integrationSha). Execute the project-wide commands from plan.md.";$finalValidation=Invoke-RalphRole $root $auditWorktree 'verifier' $context 'verifier-result.schema.json' 'read-only';if(-not[bool]$finalValidation.approved){throw "Final validation failed: $(@($finalValidation.findings)-join'; ')"};Remove-RalphAuditWorktree $root $configuration;$auditWorktree=$null
    Assert-RalphPlanDrift $state $root -RequirePlan;Assert-RalphLedgerIdentity $state $bugs bug;[void](Assert-RalphTargetDrift $root $configuration $state);$headSha=Ensure-RalphIntegrationBranch $root $configuration $state (Get-KnownMergeShas $tasks $bugs);if($headSha-cne[string]$state.integrationSha){throw 'Integration changed during final validation.'}
    $body="Completed Worktree Ralph project and verified $(@($bugs.bugs).Count) audit findings at $headSha.";$projectPr=New-RalphPullRequest $root $configuration ([string]$configuration.integrationBranch) ([string]$configuration.targetBranch) $headSha ([string]$state.targetBaseSha) 'Complete project implementation' $body;$projectPr=Complete-RalphPullRequest $root $configuration $projectPr;$finalSha=[string]$projectPr.mergeSha;Complete-ProjectCleanup $root $configuration $tasks $bugs $finalSha
    $state.stage='complete';$state.stageStatus='complete';$state.finalMergeSha=$finalSha;$state.blocker=$null;Save-RalphState $state $paths;$attempts=@($bugs.bugs|ForEach-Object{[int]$_.attemptCount});$summary=[ordered]@{completedAt=[DateTimeOffset]::UtcNow.ToString('O');auditSha=$bugs.auditSha;totalBugs=@($bugs.bugs).Count;bugsBySeverity=@($bugs.bugs|Group-Object severity|ForEach-Object{[ordered]@{severity=$_.Name;count=$_.Count}});verifiedBugs=@($bugs.bugs|Where-Object { $_.status -eq 'verified' }).Count;totalAttempts=($attempts|Measure-Object -Sum).Sum;averageAttempts=if($attempts.Count){[Math]::Round((($attempts|Measure-Object -Average).Average),2)}else{0};bugCommits=@($bugs.bugs.resultSha|Where-Object{$_});bugPullRequests=@($bugs.bugs.pullRequest|Where-Object{$_});finalValidation=$finalValidation;projectPullRequest=$projectPr;finalMergeSha=$finalSha;remainingLimitations=@()};Write-RalphSummary $paths.AuditSummary $summary;Show-RalphStatus $state $tasks $bugs;Write-Host 'PROJECT COMPLETE: audit, bug fixes, validation, merge, and cleanup succeeded.'
}
catch{if($null-ne$auditWorktree){try{Remove-RalphAuditWorktree $root $configuration}catch{}};if($null-ne$state){if($null-ne$bugs){try{Save-BugLedger $bugs $paths}catch{}};Set-RalphBlocked $state $paths 'audit' $null $_.Exception.Message 'Resolve the exact bug, provider, validation, drift, or environment blocker, then rerun audit-loop.ps1.'};throw}
finally{if($null-ne$lock){$lock.Dispose()}}
